---
title: "ggplot2 wrapped 2025"
embed-resources: true
format:
  closeread-html:
    remove-header-space: true
    css: styles.css
    narrative-font-family: Karla
    narrative-text-color-sidebar: "#212529"
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/tex-gyre-adventor" type="text/css"/>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet">
      <base target="_blank">
echo: true
warning: false
message: false
from: markdown+emoji
params: 
  executed_from: "direct_from_file"
  data_path_geom_usage: ""
  data_path_geom_details: ""
---

```{r setup}
#| echo: false
#| warning: false
#| message: false
# library("ggupset")
# library("tidyverse")
# library("ggplot2wrapped")
# library("highcharter")
# library("GPCDStools")
# library("upsetjs")
# 
# library("tidyverse")
# library("patchwork")
# library("reactable")
# library("janitor")
library("ggplot2wrapped")

if (params$executed_from == "direct_from_file") {
  load(system.file("quarto-reports", "ggplot2-unwrapped-2025_scrollytelling","data_geom_usage_example.RData", package = "ggplot2wrapped"))
  
  data_geom_usage <- data_geom_usage_example
  
  data_geom_details <- ggplot2wrapped::data_geoms
} else {
  # Because Quarto params can't be tibbles instead we use a temp dir and write
  # data files into that.
  # execute_dir = temp_dir is called to hand these files over
  data_geom_usage <- read.csv("data_geom_usage.csv")
  data_geom_details <- read.csv("data_geom_details.csv")
}
```

```{r}
print("check internal quarto")
list.files()
```

```{r}
data_geom_usage
```


```{r}
ggplot2wrapped::make_geom_icon_usage_grid(data_geom_usage, show_which_geoms = "all")
```

```{r}
data_geom_usage |> 
  ggplot2::ggplot()
```

```{r}
make_geom_icon_usage_grid(data_geom_usage, show_which_geoms = "used")
```

<!---- START: geom icon grid ---->
::::: {style="--cr-narrative-font-size:var(--size-large);--cr-narrative-sidebar-width: 2fr;--cr-section-background-color:white"}
::::{.cr-section layout="sidebar-right"}


::: {#cr-all-geom-icons .medium-fixed-text}
```{r all-geom-icons}
#| fig-width: 8
#| fig-height: 12
ggplot2wrapped::make_geom_icon_usage_grid(data_geom_usage, show_which_geoms = "all")
```
:::

::: {#cr-used-geom-icons .medium-fixed-text}
```{r used-geom-icons}
#| fig-width: 8
#| fig-height: 12
ggplot2wrapped::make_geom_icon_usage_grid(data_geom_usage, show_which_geoms = "used")
```
:::

@cr-all-geom-icons

GOT TO PLOT THEM ALL!

```{r}
#| include: false
number_geoms_in_ggplot2 <- data_geoms |> 
  dplyr::filter(package_name == "ggplot2") |> 
  dplyr::distinct(geom_name) |> 
  nrow()

number_geoms_used <- data_geom_usage |> 
  dplyr::distinct(geom_name) |> 
  nrow()
```

@cr-used-geom-icons

You used `{r} number_geoms_used` out of `{r} number_geoms_in_ggplot2` geoms from {ggplot2}!
<br>
<br>
`{r} praise::praise("${Exclamation}!")` That's over `{r} scales::label_percent()(number_geoms_used / number_geoms_in_ggplot2)`!
<br>
Let's look at your top used geoms!
::::

:::::
