---
title: "analyse_your_geom_usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{analyse_your_geom_usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2wrapped)
library("tidyverse")
library("RQuantLib")
library("statebins")
```

This utility function lists all of your code files:

```{r}
code_files <- get_code_file_info(c("~/Github/", "~/coding/r-projects-scrapbook/"), file_type = c(".qmd", ".R", ".Rmd"))
```

How many files did I create and modify this year?
```{r}
code_files %>% 
  mutate(year_modified = year(modified_time),
         year_created = year(created_time)) %>% 
  count(year_created)
```


Restricting ourselves to files created in a specific year we can find our geom_usage

```{r}
target_year <- 2022
data_target_year_geoms_raw <- code_files %>% 
  filter(year(created_time) == target_year) %>% 
   mutate(geom_usage = get_geoms_from_code_file(file_path, data_geoms)) 
```

```{r}
data_target_year_geoms_raw %>% 
  unnest(geom_usage) %>% 
  filter(n_times_used > 0)
```

## Visualisation

Replicating https://restateinsight.com/posts/general-posts/2024-12-github-contributions-plot/

```{r}

# Tibble that contains all days of the year
contributions <- expand_grid(
  date = seq(as.Date("2024-01-01"), as.Date("2024-12-31"), by = "1 day")
)

# Function to simulate number of contributions conditional on workday
sample_contribution <- Vectorize(function(x) {
  if (x == 1) {
    # Normal day of work
    rpois(1, 6.5)
  } else {
    # Small chance of working overtime on weekends or holidays
    sample(c(0, 1, 2), 1, prob = c(0.9, 0.05, 0.05))
  }}
)

contributions <- contributions |> 
  mutate(
    # Gets the number of the week in the year
    n_week = week(date),
    # Gets weekday number - Starts the week at sunday
    n_day = wday(date, week_start = 7),
    # Weekday labels for the plot
    weekday_label = wday(date, week_start = 7, label = TRUE, abbr = TRUE),
    weekday_label = fct_rev(weekday_label),
    # Month labels for the plot
    month = month(date, label = TRUE, abbr = TRUE),
    is_workday = as.numeric(RQuantLib::isBusinessDay("Brazil", date)),
    # is_weekday = if_else(n_day == 7 | n_day == 1, 0L, 1L),
    n = sample_contribution(is_workday)
  )

contributions <- contributions |> 
  mutate(
    n = if_else(n == 0, NA, n),
    n_week = if_else(n_day == 1, n_week + 1, n_week)
  )
```

Tiles

```{r}
GeomRtile <- ggplot2::ggproto(
  "GeomRtile", 
  statebins:::GeomRrect, # 1) only change compared to ggplot2:::GeomTile
                     
  extra_params = c("na.rm"),
  setup_data = function(data, params) {
    data$width <- data$width %||% params$width %||% resolution(data$x, FALSE)
    data$height <- data$height %||% params$height %||% resolution(data$y, FALSE)

    transform(data,
      xmin = x - width / 2,  xmax = x + width / 2,  width = NULL,
      ymin = y - height / 2, ymax = y + height / 2, height = NULL
    )
  },
  default_aes = ggplot2::aes(
    fill = "grey20", colour = NA, size = 0.1, linetype = 1,
    alpha = NA, width = NA, height = NA
  ),
  required_aes = c("x", "y"),

  # These aes columns are created by setup_data(). They need to be listed here so
  # that GeomRect$handle_na() properly removes any bars that fall outside the defined
  # limits, not just those for which x and y are outside the limits
  non_missing_aes = c("xmin", "xmax", "ymin", "ymax"),
  draw_key = draw_key_polygon
)

geom_rtile <- function(mapping = NULL, data = NULL,
                       stat = "identity", position = "identity",
                       radius = grid::unit(6, "pt"), # 2) add radius argument
                       ...,
                       na.rm = FALSE,
                       show.legend = NA,
                       inherit.aes = TRUE) {
  ggplot2::layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomRtile,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = rlang::list2(
      radius = radius,
      na.rm = na.rm,
      ...
    )
  )
}
```


```{r}
tab <- contributions |> 
  summarise(nmin = min(n_week), .by = "month")

ggplot(contributions, aes(n_week, weekday_label)) +
  geom_rtile(
    aes(fill = n),
    color = "white",
    radius = unit(2, "pt"),
    width = 0.9,
    height = 0.9
    ) +
  # Highlight the months on the horizontal axis
  scale_x_continuous(
    breaks = tab$nmin,
    labels = as.character(tab$month),
    position = "top",
    expand = c(0, 0)
  ) +
  # Highlight days of the week on the vertical axis
  scale_y_discrete(breaks = c("Mon", "Wed", "Fri")) +
  # Adjust color palette
  scale_fill_distiller(
    palette = "Greens",
    direction = 1,
    na.value = "gray90") +
  # Removes x and y labels
  labs(x = NULL, y = NULL) +
  # Removes the color legend
  guides(fill = "none") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    text = element_text(color = "gray10")
  )
```

## geom usage

```{r}
data_target_year_geoms_raw %>% 
  unnest(geom_usage) %>% 
  mutate(modified_date = as_date(modified_time)) %>% 
  select(geom_name, package_name, modified_time, n_times_used) %>% 
  filter(n_times_used > 0) %>% 
  mutate(modified_date = as_date(modified_time)) %>% 
  summarise(n_times_used = sum(n_times_used), .by = c(geom_name, modified_date)) %>% 
  complete(nesting(geom_name), modified_date = seq(ymd(paste0(target_year, "-01-01")), ymd(paste0(target_year, "-12-31")), by = "day"), fill = list(n_times_used = 0))
```


```{r}
data_geom_usage_by_date <- data_target_year_geoms_raw %>% 
  unnest(geom_usage) %>% 
  mutate(modified_date = as_date(modified_time)) %>% 
  select(geom_name, package_name, modified_time, n_times_used) %>% 
  filter(n_times_used > 0) %>% 
  mutate(modified_date = as_date(modified_time)) %>% 
  summarise(n_times_used = sum(n_times_used), .by = c(geom_name, modified_date)) %>% 
  complete(nesting(geom_name), modified_date = seq(ymd(paste0(target_year, "-01-01")), ymd(paste0(target_year, "-12-31")), by = "day"), fill = list(n_times_used = NA)) %>% 
  mutate(
    n_week = week(modified_date),
    n_day = wday(modified_date, week_start = 7),
    weekday_label = wday(modified_date, week_start = 7, label = TRUE, abbr = TRUE),
    weekday_label = fct_rev(weekday_label),
    month = month(modified_date, label = TRUE, abbr = TRUE),
    is_workday = as.numeric(RQuantLib::isBusinessDay("UnitedKingdom", modified_date))
  ) %>% 
  mutate(total_times_used = sum(n_times_used, na.rm = TRUE), .by = geom_name)


vec_top_5_geoms <- data_geom_usage_by_date %>% 
  distinct(geom_name, total_times_used) %>% 
  slice_max(total_times_used, n = 5) %>% 
  pull(geom_name)
```

```{r}
tab <- data_geom_usage_by_date |> 
  summarise(nmin = min(n_week), .by = "month")

data_geom_usage_by_date %>% 
  filter(geom_name %in% vec_top_5_geoms) %>% 
  mutate(geom_name = fct_reorder(geom_name, total_times_used),
         geom_name = fct_rev(geom_name)) %>% 
  ggplot() +
  aes(n_week, weekday_label) +
  geom_rtile(
    aes(fill = n_times_used),
    color = "white",
    radius = unit(2, "pt"),
    width = 0.9,
    height = 0.9
    ) +
  # Highlight the months on the horizontal axis
  scale_x_continuous(
    breaks = tab$nmin,
    labels = as.character(tab$month),
    position = "top",
    expand = c(0, 0)
  ) +
  facet_grid(geom_name ~ .,
             switch = 'y') +
  # Highlight days of the week on the vertical axis
  scale_y_discrete(breaks = c("Mon", "Wed", "Fri")) +
  # Adjust color palette
  scale_fill_binned(
    palette = "Greens",
    n.breaks = 4,
    # direction = 1,
    na.value = "gray90") +
  # Removes x and y labels
  labs(x = NULL, y = NULL) +
  # Removes the color legend
  guides(fill = "none") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    text = element_text(color = "gray10"),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0,
                                     size = 12)
  )
```

